---
title: "Lab7"
author: "Alain Perez"
date: "3/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(babynames)
data(babynames)
data(births)

head(births)
```

```{r}
ssa_births<- babynames%>%
  rename(num_births = n)%>%
  group_by(year)%>%
  summarize(
    distinct_name_sex_combos=n(),
    births = sum(num_births))%>%
  filter(year <=2012)
head(ssa_births)
    
```

```{r}
census_births<-births
head(ssa_births)
head(census_births)
```
Comparing the two datasets

```{r}
ssa_births$year
census_births$year
```


```{r}
joined_via_inner<-ssa_births%>%
  inner_join(census_births, by="year")
head(joined_via_inner)
```

```{r}
joined_via_inner$year
```

Joining through the left

```{r}
joined_via_left<-
  ssa_births%>%
  left_join(census_births, by= "year")
  joined_via_left%>% filter(year<1919)
  joined_via_left%>% filter(year > 2008)
  unique(joined_via_left$year)
```
Filtering out missing values

```{r}
filter(is.na(births.x))
```

```{r}
joined_via_left%>%
filter(is.na(births.y))
```

Now we will look at full join


```{r}
joined_via_full<-ssa_births%>%
  full_join(census_births, by ="year")
joined_via_full$year
joined_via_full%>%
  filter(is.na(births.x))
joined_via_full%>%
  filter(is.na(births.y))
```

lets anaylze the data

```{r}
joined_via_full%>%
  ggplot(aes(x=births.x, y=births.y))+geom_point()
```

##Exercise 1##
The two data sets are different because the first one accounts for the lower half of the data points and the second accounts for the right hand side of the data points and the upper data points as well.

##Exercise 2##
```{r}
library(nycflights13)

```